apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  {{- if .Values.redis.storage.volumeName }}
  volumeName: {{ .Values.redis.storage.volumeName }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.storage.size }}
