apiVersion: v1
kind: Secret
metadata:
  name: overleaf-secret
type: Opaque
stringData:
  # Add any secret environment variables here
  # Example:
  # OVERLEAF_SITE_URL: "https://overleaf.example.com"
  # OVERLEAF_ADMIN_EMAIL: "admin@example.com"
  # OVERLEAF_EMAIL_FROM_ADDRESS: "noreply@example.com"
  # OVERLEAF_EMAIL_SMTP_HOST: "smtp.example.com"
  # OVERLEAF_EMAIL_SMTP_PORT: "587"
  # OVERLEAF_EMAIL_SMTP_USER: "user"
  # OVERLEAF_EMAIL_SMTP_PASS: "password"
