ingress:
  host:
  ingressClassName: traefik

oidc:
  enabled: false
  provider:
  authDomain:
  clientId:
  clientSecret:

mongodb:
  port:
  storage:
    volumeName: ""
    size: 1Gi

redis:
  storage:
    volumeName: ""
    size: 0.5Gi

overleaf:
  storage:
    size: 1Gi

docker:
  storage:
    size: 10Gi
